[package]
name = "binary-vulture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-maps = "0.3.2"
process-memory = "0.5.0"
rayon = "1.8.1"
